const products = [
  {
    type: "stationery",
    original_price: 12.99,
    discounted_price: 9.99,
    availability: "In Stock",
    title: "Notebook",
    main_image: "images/notebook_main.jpg",
    other_images: ["images/notebook_1.jpg", "images/notebook_2.jpg"],
  },
  {
    type: "office",
    original_price: 199.99,
    discounted_price: 149.99,
    availability: "Out of Stock",
    title: "Office Chair",
    main_image: "images/office_chair_main.jpg",
    other_images: ["images/office_chair_1.jpg", "images/office_chair_2.jpg"],
  },
  {
    type: "home",
    original_price: 299.99,
    discounted_price: 249.99,
    availability: "In Stock",
    title: "Coffee Maker",
    main_image: "images/coffee_maker_main.jpg",
    other_images: ["images/coffee_maker_1.jpg", "images/coffee_maker_2.jpg"],
  },
  {
    type: "fashion",
    original_price: 59.99,
    discounted_price: 39.99,
    availability: "In Stock",
    title: "Denim Jacket",
    main_image: "images/denim_jacket_main.jpg",
    other_images: ["images/denim_jacket_1.jpg", "images/denim_jacket_2.jpg"],
  },
  {
    type: "stationery",
    original_price: 24.99,
    discounted_price: 19.99,
    availability: "In Stock",
    title: "Desk Organizer",
    main_image: "images/desk_organizer_main.jpg",
    other_images: [
      "images/desk_organizer_1.jpg",
      "images/desk_organizer_2.jpg",
    ],
  },
  {
    type: "office",
    original_price: 99.99,
    discounted_price: 79.99,
    availability: "In Stock",
    title: "Desk Lamp",
    main_image: "images/desk_lamp_main.jpg",
    other_images: ["images/desk_lamp_1.jpg", "images/desk_lamp_2.jpg"],
  },
  {
    type: "home",
    original_price: 89.99,
    discounted_price: 69.99,
    availability: "Out of Stock",
    title: "Blender",
    main_image: "images/blender_main.jpg",
    other_images: ["images/blender_1.jpg", "images/blender_2.jpg"],
  },
  {
    type: "fashion",
    original_price: 79.99,
    discounted_price: 59.99,
    availability: "In Stock",
    title: "Sneakers",
    main_image: "images/sneakers_main.jpg",
    other_images: ["images/sneakers_1.jpg", "images/sneakers_2.jpg"],
  },
  {
    type: "stationery",
    original_price: 14.99,
    discounted_price: 11.99,
    availability: "In Stock",
    title: "Pen Set",
    main_image: "images/pen_set_main.jpg",
    other_images: ["images/pen_set_1.jpg", "images/pen_set_2.jpg"],
  },
  {
    type: "office",
    original_price: 499.99,
    discounted_price: 449.99,
    availability: "In Stock",
    title: "Standing Desk",
    main_image: "images/standing_desk_main.jpg",
    other_images: ["images/standing_desk_1.jpg", "images/standing_desk_2.jpg"],
  },
  {
    type: "home",
    original_price: 49.99,
    discounted_price: 39.99,
    availability: "In Stock",
    title: "Toaster",
    main_image: "images/toaster_main.jpg",
    other_images: ["images/toaster_1.jpg", "images/toaster_2.jpg"],
  },
  {
    type: "fashion",
    original_price: 99.99,
    discounted_price: 79.99,
    availability: "In Stock",
    title: "Leather Belt",
    main_image: "images/leather_belt_main.jpg",
    other_images: ["images/leather_belt_1.jpg", "images/leather_belt_2.jpg"],
  },
  {
    type: "stationery",
    original_price: 19.99,
    discounted_price: 14.99,
    availability: "Out of Stock",
    title: "Highlighter Set",
    main_image: "images/highlighter_set_main.jpg",
    other_images: [
      "images/highlighter_set_1.jpg",
      "images/highlighter_set_2.jpg",
    ],
  },
  {
    type: "office",
    original_price: 29.99,
    discounted_price: 24.99,
    availability: "In Stock",
    title: "Mouse Pad",
    main_image: "images/mouse_pad_main.jpg",
    other_images: ["images/mouse_pad_1.jpg", "images/mouse_pad_2.jpg"],
  },
  {
    type: "home",
    original_price: 199.99,
    discounted_price: 179.99,
    availability: "In Stock",
    title: "Air Purifier",
    main_image: "images/air_purifier_main.jpg",
    other_images: ["images/air_purifier_1.jpg", "images/air_purifier_2.jpg"],
  },
  {
    type: "fashion",
    original_price: 49.99,
    discounted_price: 34.99,
    availability: "In Stock",
    title: "T-shirt",
    main_image: "images/tshirt_main.jpg",
    other_images: ["images/tshirt_1.jpg", "images/tshirt_2.jpg"],
  },
  {
    type: "stationery",
    original_price: 9.99,
    discounted_price: 7.99,
    availability: "In Stock",
    title: "Stapler",
    main_image: "images/stapler_main.jpg",
    other_images: ["images/stapler_1.jpg", "images/stapler_2.jpg"],
  },
  {
    type: "office",
    original_price: 79.99,
    discounted_price: 59.99,
    availability: "Out of Stock",
    title: "Paper Shredder",
    main_image: "images/paper_shredder_main.jpg",
    other_images: [
      "images/paper_shredder_1.jpg",
      "images/paper_shredder_2.jpg",
    ],
  },
  {
    type: "home",
    original_price: 129.99,
    discounted_price: 99.99,
    availability: "In Stock",
    title: "Vacuum Cleaner",
    main_image: "images/vacuum_cleaner_main.jpg",
    other_images: [
      "images/vacuum_cleaner_1.jpg",
      "images/vacuum_cleaner_2.jpg",
    ],
  },
  {
    type: "fashion",
    original_price: 149.99,
    discounted_price: 129.99,
    availability: "In Stock",
    title: "Wristwatch",
    main_image: "images/wristwatch_main.jpg",
    other_images: ["images/wristwatch_1.jpg", "images/wristwatch_2.jpg"],
  },
  {
    type: "stationery",
    original_price: 5.99,
    discounted_price: 4.99,
    availability: "In Stock",
    title: "Glue Stick",
    main_image: "images/glue_stick_main.jpg",
    other_images: ["images/glue_stick_1.jpg", "images/glue_stick_2.jpg"],
  },
  {
    type: "office",
    original_price: 39.99,
    discounted_price: 29.99,
    availability: "In Stock",
    title: "Desk Fan",
    main_image: "images/desk_fan_main.jpg",
    other_images: ["images/desk_fan_1.jpg", "images/desk_fan_2.jpg"],
  },
  {
    type: "home",
    original_price: 79.99,
    discounted_price: 59.99,
    availability: "In Stock",
    title: "Electric Kettle",
    main_image: "images/electric_kettle_main.jpg",
    other_images: [
      "images/electric_kettle_1.jpg",
      "images/electric_kettle_2.jpg",
    ],
  },
  {
    type: "fashion",
    original_price: 69.99,
    discounted_price: 49.99,
    availability: "In Stock",
    title: "Scarf",
    main_image: "images/scarf_main.jpg",
    other_images: ["images/scarf_1.jpg", "images/scarf_2.jpg"],
  },
  {
    type: "stationery",
    original_price: 2.99,
    discounted_price: 1.99,
    availability: "In Stock",
    title: "Eraser",
    main_image: "images/eraser_main.jpg",
    other_images: ["images/eraser_1.jpg", "images/eraser_2.jpg"],
  },
  {
    type: "office",
    original_price: 69.99,
    discounted_price: 54.99,
    availability: "Out of Stock",
    title: "Keyboard",
    main_image: "images/keyboard_main.jpg",
    other_images: ["images/keyboard_1.jpg", "images/keyboard_2.jpg"],
  },
  {
    type: "home",
    original_price: 149.99,
    discounted_price: 129.99,
    availability: "In Stock",
    title: "Microwave Oven",
    main_image: "images/microwave_oven_main.jpg",
    other_images: [
      "images/microwave_oven_1.jpg",
      "images/microwave_oven_2.jpg",
    ],
  },
  {
    type: "fashion",
    original_price: 89.99,
    discounted_price: 69.99,
    availability: "In Stock",
    title: "Handbag",
    main_image: "images/handbag_main.jpg",
    other_images: ["images/handbag_1.jpg", "images/handbag_2.jpg"],
  },
  {
    type: "stationery",
    original_price: 34.99,
    discounted_price: 29.99,
    availability: "In Stock",
    title: "Art Supplies Kit",
    main_image: "images/art_supplies_kit_main.jpg",
    other_images: [
      "images/art_supplies_kit_1.jpg",
      "images/art_supplies_kit_2.jpg",
    ],
  },
  {
    type: "office",
    original_price: 19.99,
    discounted_price: 14.99,
    availability: "In Stock",
    title: "Notebook Stand",
    main_image: "images/notebook_stand_main.jpg",
    other_images: [
      "images/notebook_stand_1.jpg",
      "images/notebook_stand_2.jpg",
    ],
  },
  {
    type: "home",
    original_price: 59.99,
    discounted_price: 49.99,
    availability: "In Stock",
    title: "Iron",
    main_image: "images/iron_main.jpg",
    other_images: ["images/iron_1.jpg", "images/iron_2.jpg"],
  },
];

export default products;
